"""Subclass of MainFrameBase, which is generated by wxFormBuilder."""

import wx
from DataModel.ProductGroupConstants import *
from DataModel.Ticket import Ticket
import GeneratedGui

# Implementing MainFrameBase
from Gui import *
from Gui.PanelDrank import PanelDrank
from Gui.PanelFrieten import PanelFrieten
from Gui.PanelSaus import PanelSaus
from Gui.PanelSnacks import PanelSnacks

class MainFrame( GeneratedGui.MainFrameBase ):
    def __init__( self, parent ):
        GeneratedGui.MainFrameBase.__init__( self, parent)
        self.pnlGroepen.Enabled=False
        self.pnlRekening.Enabled=False
        self.pnlRekening.Enabled=False
        self.btnNieuwTicket.Enabled=True

    # Handlers for MainFrameBase events.
    def SetProductPanel(self, panelType):
        children = self.pnlProducten.GetChildren()
        for child in children:
            #self.pnlProducten.RemoveChild(child)
            child.Destroy()

        self.pnlProducten.Layout()

        bsProducten = wx.BoxSizer(wx.VERTICAL)
        if panelType == Frieten:
            self.ProductPanel = PanelFrieten(self.pnlProducten)
        elif panelType == Snacks:
            self.ProductPanel = PanelSnacks(self.pnlProducten)
        elif panelType == Dranken:
            self.ProductPanel = PanelDrank(self.pnlProducten)
        elif panelType == Koude_sauzen:
            self.ProductPanel = PanelSaus(self.pnlProducten)

        try:
            bsProducten.Add(self.ProductPanel, 1, wx.EXPAND | wx.ALL, 5)

            self.pnlProducten.SetSizer(bsProducten)
            self.pnlProducten.Layout()
            bsProducten.Fit(self.pnlProducten)
        except:
            pass

    def btnNieuwTicketOnButtonClick( self, event ):
        self.pnlGroepen.Enabled=True
        self.pnlProducten.Enabled=True
        self.pnlRekening.Enabled=True
        self.btnNieuwTicket.Enabled=False
        ticket = Ticket()
        ticket.CreateNewTicket()

    def btnAnnulerenOnButtonClick( self, event ):
        self.pnlGroepen.Enabled=False
        self.pnlProducten.Enabled=False
        self.pnlRekening.Enabled=False
        self.btnNieuwTicket.Enabled=True
        ticket = Ticket()
        ticket.CancelTicket()

    def btnAfrekekenOnButtonClick( self, event ):
        self.pnlGroepen.Enabled=False
        self.pnlProducten.Enabled=False
        self.pnlRekening.Enabled=False
        self.btnNieuwTicket.Enabled=True
        ticket = Ticket()
        ticket.PayTicket()

    def btnFrietenOnButtonClick( self, event ):
        self.SetProductPanel(Frieten)

    def btnSnacksOnButtonClick( self, event ):
        self.SetProductPanel(Snacks)

    def btnDrankOnButtonClick( self, event ):
        self.SetProductPanel(Dranken)

    def btnSausOnButtonClick( self, event ):
        self.SetProductPanel(Koude_sauzen)


