"""Subclass of MainFrameBase, which is generated by wxFormBuilder."""

import wx
from DataModel.ScreenGroup import ScreenGroup
from DataModel.Ticket import Ticket
import GeneratedGui

# Implementing MainFrameBase
from Gui import *

class MainFrame( GeneratedGui.MainFrameBase ):
    _selectedGroup=0

    def __init__( self, parent ):
        GeneratedGui.MainFrameBase.__init__( self, parent)
        self.pnlGroepen.Enabled=False
        self.pnlProducten.Enabled=False
        self.pnlRekening.Enabled=False
        self.pnlRekening.Enabled=False
        self.btnNieuwTicket.Enabled=True

        #fill group buttons
        self.btnGroupOne.Enabled =False
        self.btnGroupOne.SetLabel("")
        self.btnGroupTwo.Enabled=False
        self.btnGroupTwo.SetLabel("")
        self.btnGroupThree.Enabled=False
        self.btnGroupThree.SetLabel("")
        self.btnGroupFour.Enabled=False
        self.btnGroupFour.SetLabel("")
        self.btnGroupFive.Enabled=False
        self.btnGroupFive.SetLabel("")
        self.btnGroupSix.Enabled=False
        self.btnGroupSix.SetLabel("")
        self.btnGroupSeven.Enabled=False
        self.btnGroupSeven.SetLabel("")

        i=1
        for name in ScreenGroup().fetchall():
            if i==1:
                self.btnGroupOne.SetLabel(name[1])
            elif i==2:
                self.btnGroupTwo.SetLabel(name[1])
            elif i==3:
                self.btnGroupThree.SetLabel(name[1])
            elif i==4:
                self.btnGroupFour.SetLabel(name[1])
            elif i==5:
                self.btnGroupFive.SetLabel(name[1])
            elif i==6:
                self.btnGroupSix.SetLabel(name[1])
            elif i==7:
                self.btnGroupSeven.SetLabel(name[1])

            i=i+1



    # Handlers for MainFrameBase events.
    def btnNieuwTicketOnButtonClick( self, event ):
        self.pnlGroepen.Enabled=True
        self.pnlProducten.Enabled=True
        self.pnlRekening.Enabled=True
        self.btnNieuwTicket.Enabled=False
        ticket = Ticket()
        ticket.CreateNewTicket()

    def btnAnnulerenOnButtonClick( self, event ):
        self.pnlGroepen.Enabled=False
        self.pnlProducten.Enabled=False
        self.pnlRekening.Enabled=False
        self.btnNieuwTicket.Enabled=True
        ticket = Ticket()
        ticket.CancelTicket()

    def btnAfrekekenOnButtonClick( self, event ):
        self.pnlGroepen.Enabled=False
        self.pnlProducten.Enabled=False
        self.pnlRekening.Enabled=False
        self.btnNieuwTicket.Enabled=True
        ticket = Ticket()
        ticket.PayTicket()

    def btnGroupOneOnButtonClick( self, event ):
        self._selectedGroup=1

    def btnGroupTwoOnButtonClick( self, event ):
        self._selectedGroup=2

    def btnGroupThreeOnButtonClick( self, event ):
        self._selectedGroup=3

    def btnGroupFourOnButtonClick( self, event ):
        self._selectedGroup=4

    def btnGroupFiveOnButtonClick( self, event ):
        self._selectedGroup=5

    def btnGroupSixOnButtonClick( self, event ):
        self._selectedGroup=6

    def btnGroupSevenOnButtonClick( self, event ):
        self._selectedGroup=7

    def _updateProductButtons


