"""Subclass of PanelSnacksBase, which is generated by wxFormBuilder."""

import wx
import GeneratedGui

# Implementing PanelSnacksBase
class PanelSnacks( GeneratedGui.PanelSnacksBase ):
	def __init__( self, parent ):
		GeneratedGui.PanelSnacksBase.__init__( self, parent )
	
	# Handlers for PanelSnacksBase events.
	def btnFrikandelOnButtonClick( self, event ):
		# TODO: Implement btnFrikandelOnButtonClick
		pass
	
	def btnMexicanoOnButtonClick( self, event ):
		# TODO: Implement btnMexicanoOnButtonClick
		pass
	
	def btnKippetsOnButtonClick( self, event ):
		# TODO: Implement btnKippetsOnButtonClick
		pass
	
	def btnMammoetOnButtonClick( self, event ):
		# TODO: Implement btnMammoetOnButtonClick
		pass
	
	
