"""Subclass of PanelHamburgersBase, which is generated by wxFormBuilder."""

import wx
import GeneratedGui

# Implementing PanelHamburgersBase
class PanelHamburgers( GeneratedGui.PanelHamburgersBase ):
	def __init__( self, parent ):
		GeneratedGui.PanelHamburgersBase.__init__( self, parent )
	
