"""Subclass of PanelFrietenBase, which is generated by wxFormBuilder."""

import wx
import GeneratedGui

# Implementing PanelFrietenBase
class PanelFrieten( GeneratedGui.PanelFrietenBase ):
	def __init__( self, parent ):
		GeneratedGui.PanelFrietenBase.__init__( self, parent )
	
