"""Subclass of PanelWarmeSausBase, which is generated by wxFormBuilder."""

import wx
import GeneratedGui

# Implementing PanelWarmeSausBase
class PanelWarmeSaus( GeneratedGui.PanelWarmeSausBase ):
	def __init__( self, parent ):
		GeneratedGui.PanelWarmeSausBase.__init__( self, parent )
	
