"""Subclass of PanelEigenBereidingenBase, which is generated by wxFormBuilder."""

import wx
import GeneratedGui

# Implementing PanelEigenBereidingenBase
class PanelEigenBereidingen( GeneratedGui.PanelEigenBereidingenBase ):
	def __init__( self, parent ):
		GeneratedGui.PanelEigenBereidingenBase.__init__( self, parent )
        
	
