"""Subclass of PanelDrankBase, which is generated by wxFormBuilder."""

import wx
import GeneratedGui

# Implementing PanelDrankBase
class PanelDrank( GeneratedGui.PanelDrankBase ):
	def __init__( self, parent ):
		GeneratedGui.PanelDrankBase.__init__( self, parent )
	
