"""Subclass of PanelSausBase, which is generated by wxFormBuilder."""

import wx
import GeneratedGui

# Implementing PanelSausBase
class PanelSaus( GeneratedGui.PanelSausBase ):
	def __init__( self, parent ):
		GeneratedGui.PanelSausBase.__init__( self, parent )
	
